apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-k8s
  template:
    metadata:
      labels:
        app: test-k8s
    spec:
      containers:
      - name: test-k8s
        image: umesh3149044/test-k8s
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3005
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: test-k8s-service
spec:
  type: LoadBalancer
  selector:
    app: test-k8s
  ports:
  - name: http
    port: 3005
    targetPort: 3005