version: '3.7'

services:
  test-k8s:
    container_name: test-k8s
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3005:3005
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: node app.js